name: deployable_security_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_local_notifications: ^17.2.4
  flutter_local_notifications_platform_interface: ^7.0.0+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
