name: deployable_security_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_local_notifications: ^17.2.4
  flutter_local_notifications_platform_interface: ^7.0.0+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  loading_animation_widget: ^1.2.0+4
  network_info_plus: ^5.0.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/dssLogo.png
    - assets/images/colin.png
    - assets/images/dylan.png
    - assets/images/phillip.png
    - assets/images/jaxon.png
    - assets/animations/